"""Niri configuration fragment generator (docs/10 §13–14, docs/12 §16–17).

Generates an Omivoid-owned Niri bindings fragment from the action registry:

    ~/.config/omivoid/generated/niri/bindings.kdl

Rules:
- generated file is clearly marked;
- source action IDs are documented per binding;
- only Omivoid-managed bindings are included;
- native Niri actions compile directly to KDL (Contract 4);
- application actions route through the Omivoid runner (registry → adapter);
- chords (Super+A,E) are shell-handled and never generated into Niri;
- invalid output must not replace working config (validate before write).
"""

from __future__ import annotations

import subprocess
import tempfile
from pathlib import Path

from .registry import Registry, repo_root, user_config_dir

GENERATED_HEADER = """// Generated by Omivoid.
// Source: Action Registry.
// Do not edit directly.
// Fix the registry or the generator instead."""

DEFAULT_OUTPUT = user_config_dir() / "generated" / "niri" / "bindings.kdl"

# Human-friendly registry key names → XKB key names used by Niri.
XKB_KEY_ALIASES = {
    "Super": "Mod",  # Niri's default modifier
    "Enter": "Return",
    "Esc": "Escape",
    "Space": "space",
}

def binding_to_kdl(binding: str) -> str:
    """Convert an Omivoid binding string to Niri KDL syntax.

    Super is Niri's default Mod modifier; key names are converted to
    XKB names (Enter → Return, Space → space, ...).
    """
    tokens = binding.split("+")
    mapped = [XKB_KEY_ALIASES.get(t, t) for t in tokens]
    return "+".join(mapped)


# Keys claimed by DMS's generated binds.kdl (Stage 14, dms-evaluation.md §4.2).
# The Omivoid generator must not double-bind these. DMS owns shell-level keys
# (launcher, clipboard, notifications, lock, media keys) and native Niri
# navigation keys; Omivoid owns action keys (app launch, help/search).
# Written in registry/binds.kdl notation; converted to canonical KDL form so
# the exclusion check matches binding_to_kdl output exactly.
_DMS_CLAIMED_KEYS_SOURCE: frozenset[str] = frozenset({
    # System & overview
    "Mod+O", "Mod+Tab", "Mod+Shift+Slash",
    # Application launchers
    "Mod+T", "Mod+Space", "Alt+Space", "Mod+V", "Mod+M",
    "Super+X", "Mod+Comma", "Mod+Y", "Mod+N", "Mod+Shift+N",
    # Security
    "Mod+Alt+L", "Mod+Shift+E", "Ctrl+Alt+Delete",
    # Audio controls
    "XF86AudioRaiseVolume", "XF86AudioLowerVolume", "XF86AudioMute",
    "XF86AudioMicMute", "XF86AudioPause", "XF86AudioPlay",
    "XF86AudioPrev", "XF86AudioNext",
    "Ctrl+XF86AudioRaiseVolume", "Ctrl+XF86AudioLowerVolume",
    # Brightness controls
    "XF86MonBrightnessUp", "XF86MonBrightnessDown",
    # Window management
    "Mod+Q", "Mod+F", "Mod+Shift+F", "Mod+Shift+T", "Mod+Shift+V",
    "Mod+W", "Mod+Shift+W",
    # Focus navigation
    "Mod+Left", "Mod+Down", "Mod+Up", "Mod+Right",
    "Mod+H", "Mod+J", "Mod+L",
    # Window movement
    "Mod+Shift+Left", "Mod+Shift+Down", "Mod+Shift+Up", "Mod+Shift+Right",
    "Mod+Shift+H", "Mod+Shift+J", "Mod+Shift+K", "Mod+Shift+L",
    # Column navigation
    "Mod+Home", "Mod+End", "Mod+Ctrl+Home", "Mod+Ctrl+End",
    # Monitor navigation
    "Mod+Ctrl+Left", "Mod+Ctrl+Right", "Mod+Ctrl+H", "Mod+Ctrl+J",
    "Mod+Ctrl+K", "Mod+Ctrl+L",
    # Move to monitor
    "Mod+Shift+Ctrl+Left", "Mod+Shift+Ctrl+Down", "Mod+Shift+Ctrl+Up",
    "Mod+Shift+Ctrl+Right", "Mod+Shift+Ctrl+H", "Mod+Shift+Ctrl+J",
    "Mod+Shift+Ctrl+K", "Mod+Shift+Ctrl+L",
    # Workspace navigation
    "Mod+Page_Down", "Mod+Page_Up", "Mod+U", "Mod+I",
    "Mod+Ctrl+Down", "Mod+Ctrl+Up", "Mod+Ctrl+U", "Mod+Ctrl+I",
    # Workspace management
    "Ctrl+Shift+R",
    # Move workspaces
    "Mod+Shift+Page_Down", "Mod+Shift+Page_Up", "Mod+Shift+U", "Mod+Shift+I",
    # Numbered workspaces
    *(f"Mod+{i}" for i in range(1, 10)),
    *(f"Mod+Shift+{i}" for i in range(1, 10)),
    # Column management
    "Mod+BracketLeft", "Mod+BracketRight", "Mod+Period",
    # Sizing & layout
    "Mod+R", "Mod+Shift+R", "Mod+Ctrl+R", "Mod+Ctrl+F", "Mod+C", "Mod+Ctrl+C",
    # Manual sizing
    "Mod+Minus", "Mod+Equal", "Mod+Shift+Minus", "Mod+Shift+Equal",
    # Screenshots
    "XF86Launch1", "Ctrl+XF86Launch1", "Alt+XF86Launch1",
    "Print", "Ctrl+Print", "Alt+Print",
    # Display profiles
    "Mod+P",
    # System controls
    "Mod+Escape", "Mod+Shift+P",
})

DMS_CLAIMED_KEYS: frozenset[str] = frozenset(
    binding_to_kdl(k) for k in _DMS_CLAIMED_KEYS_SOURCE
)


def is_chord(binding: str) -> bool:
    """A chord (Super+A,E) is handled by the shell, not by Niri."""
    return "," in binding


def generate_niri_fragment(registry: Registry, omivoid_cli: str) -> str:
    """Generate the Omivoid Niri bindings fragment."""
    lines = [GENERATED_HEADER, ""]
    lines.append("// Omivoid-managed bindings. Source action IDs are documented per binding.")
    lines.append("")
    lines.append("binds {")

    actions = sorted(registry.actions.values(), key=lambda a: a.id)
    for action in actions:
        if not action.keys:
            continue
        for key in action.keys:
            if is_chord(key):
                continue  # chords are shell-handled
            kdl_key = binding_to_kdl(key)
            if kdl_key in DMS_CLAIMED_KEYS:
                continue  # DMS owns this key (dms-evaluation.md §4.2)

            if action.adapter == "niri.native" and action.arguments.get("action"):
                niri_action = action.arguments["action"]
                lines.append(f"    // {action.id}")
                lines.append(f"    {kdl_key} {{")
                lines.append(f"        {niri_action}")
                lines.append("    }")
                lines.append("")
            elif action.adapter == "app.launch":
                lines.append(f"    // {action.id}")
                lines.append(f"    {kdl_key} {{")
                lines.append(
                    f'        spawn "{omivoid_cli}" "action" "run" "{action.id}"'
                )
                lines.append("    }")
                lines.append("")
            elif action.arguments.get("command") or action.command:
                # Shell-handled command declared by the action. The
                # `arguments.command` form is used by shell.* adapters; the
                # top-level `command` form is used by the `command` adapter.
                cmd = action.arguments.get("command") or action.command
                spawn_args = " ".join(f'"{a}"' for a in cmd)
                lines.append(f"    // {action.id}")
                lines.append(f"    {kdl_key} {{")
                lines.append(f"        spawn {spawn_args}")
                lines.append("    }")
                lines.append("")
            # shell.* adapters without command are handled by the shell, not here.

    lines.append("}")
    return "\n".join(lines)


def validate_fragment(fragment_path: Path) -> tuple[bool, str]:
    """Validate a generated fragment with `niri validate`.

    Uses a temporary wrapper config that includes the fragment, so the
    fragment is checked in isolation without touching the active config.
    """
    try:
        with tempfile.NamedTemporaryFile(
            suffix=".kdl", mode="w", delete=False
        ) as f:
            f.write(f'include "{fragment_path}"\n')
            wrapper = f.name
        result = subprocess.run(
            ["niri", "validate", "-c", wrapper],
            capture_output=True,
            text=True,
            timeout=15,
        )
        output = (result.stdout + result.stderr).strip()
        return result.returncode == 0, output
    except FileNotFoundError:
        return False, "niri is not available"
    except subprocess.TimeoutExpired:
        return False, "niri validate timed out"
    finally:
        Path(wrapper).unlink(missing_ok=True)


def build_fragment(
    registry: Registry,
    output: Path = DEFAULT_OUTPUT,
    dry_run: bool = False,
) -> tuple[bool, str]:
    """Build (and optionally write) the generated Niri fragment.

    Returns (ok, message). Never writes invalid output.
    """
    omivoid_cli = str(repo_root() / "cli" / "omivoid")
    fragment = generate_niri_fragment(registry, omivoid_cli)

    if dry_run:
        return True, fragment

    output = Path(output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(fragment)

    ok, message = validate_fragment(output)
    if not ok:
        # Do not leave an invalid generated file in place.
        output.unlink(missing_ok=True)
        return False, f"generated fragment failed validation:\n{message}"

    return True, f"wrote {output}\n{message}"